# Generated by Django 3.1.2 on 2020-10-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='new_project/')),
                ('description', models.TextField(max_length=200)),
                ('link', models.URLField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
